// Lista de retos y premios de la despedida.
// Para editar retos o premios, simplemente cambia el texto aqui.
// "id" no se debe repetir ni reordenar una vez publicada la app,
// porque el progreso guardado en Firebase se referencia por id.
const CHALLENGES = [
  { id: 1, text: "Hacer de perro durante 2 minutos", prize: "1 Copa" },
  { id: 2, text: "Atarlo con cinta americana y no soltarlo hasta pagar un rescate", prize: "Comida/cena" },
  { id: 3, text: "Pintarse las uñas de una mano", prize: "Chupito" },
  { id: 4, text: "Pedir calos a extraños que estén fumando", prize: "Chupito" },
  { id: 5, text: "Conseguir buches de copas de mujeres (si te haces hidalgo tienes extra)", prize: "Copa" },
  { id: 6, text: "Tirarte desnudo del barco", prize: "3 Copas" },
  { id: 7, text: "Realizar un brindis random", prize: "Chupito" },
  { id: 8, text: "Conseguir 10 firmas de mujeres", prize: "1 Copa" },
  { id: 9, text: "Convencer a alguien para que le enseñe un paso de baile y repetirlo/bailar juntos", prize: "Chupito" },
  { id: 10, text: "Conseguir vídeos felicitándole la boda", prize: "1 Chupito" },
  { id: 11, text: "Pedir una copa exacta con gestos", prize: "1 Chupito" },
  { id: 12, text: "Selfie con un policía", prize: "2 Copas" },
  { id: 13, text: "Hacerte un tatuaje", prize: "3 Copas" },
  { id: 14, text: "Hacer una actuación durante 2 minutos en un lugar público", prize: "1 Copa" },
  { id: 15, text: "Hacer una conga de 10 personas sin contarnos", prize: "1 Copa" },
  { id: 16, text: "Robar una escobilla de váter (extra si está sucia)", prize: "Ronda de cervezas" },
  { id: 17, text: "1 minuto de plancha", prize: "Ronda de cervezas" },
  { id: 18, text: "Hacer una pirámide humana con desconocidos (extra por 5 personas)", prize: "1 Copa" },
  { id: 19, text: "Mear en la barra de una discoteca", prize: "1 Comida" },
  { id: 20, text: "Estar 1 hora sin fumar", prize: "1 Copa" },
  { id: 21, text: "Desayunar whiskey con cereales", prize: "1 Comida" },
  { id: 22, text: "Probar unas sandalias del paseo marítimo y hacer amago de salir a correr", prize: "Copa" },
  { id: 23, text: "Gritar en medio de una comida", prize: "Copa" },
  { id: 24, text: "Cantarle cumpleaños feliz a un desconocido", prize: "Ronda de cervezas" },
  { id: 25, text: "Conseguir un after", prize: "3 Copas" },
  { id: 26, text: "Conseguir un baile erótico (a más humillante mejor)", prize: "Dependiendo de lo visto" },
  { id: 27, text: "Dejarse duchar", prize: "5 Copas" },
  { id: 28, text: "Cambiarse la camiseta con alguien y no devolvérsela", prize: "2 Copas" },
  { id: 29, text: "Vender dos paquetes de pañuelos en un semáforo", prize: "Ronda de cervezas" },
  { id: 30, text: "Fumarse un cigarro entero por la nariz", prize: "Cáncer de pulmón" },
  { id: 31, text: "Arrestar a alguien", prize: "2 Copas" },
  { id: 32, text: "Tirarse una cerveza entera encima", prize: "Ronda de cervezas" },
  { id: 33, text: "Tirarse del catamarán en marcha", prize: "3 Copas" },
  { id: 34, text: "Tirarte en bomba en una piscina de beach club/discoteca", prize: "Ronda de cervezas" },
  { id: 35, text: "Sacar un dospa con tu cuñao", prize: "2 Copas" },
  { id: 36, text: "RETO ESTRELLA: montarlo el sábado en un bus a tomar por culo", prize: "🌟 La leyenda del bus — ¡premio al gusto del grupo!", star: true },
];
